# Generated by Django 5.1.3 on 2025-01-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookmark",
            old_name="profile",
            new_name="profile_id",
        ),
        migrations.RenameField(
            model_name="bookmarklist",
            old_name="bookmark",
            new_name="bookmark_id",
        ),
        migrations.RenameField(
            model_name="bookmarklist",
            old_name="place_code",
            new_name="place_id",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="place_code",
            new_name="place_id",
        ),
        migrations.RenameField(
            model_name="settings",
            old_name="country",
            new_name="country_id",
        ),
        migrations.RenameField(
            model_name="settings",
            old_name="profile",
            new_name="profile_id",
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="country",
        ),
        migrations.RemoveField(
            model_name="bookmarklist",
            name="country",
        ),
        migrations.RemoveField(
            model_name="place",
            name="close_date",
        ),
        migrations.RemoveField(
            model_name="place",
            name="open_date",
        ),
    ]
