# Generated by Django 5.1.3 on 2025-01-03 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_bookmark_created_at_bookmarklist_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={"managed": False},
        ),
    ]
