# Generated by Django 5.1.3 on 2025-01-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_bookmark_options_alter_bookmarklist_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="user",
        ),
    ]
