# Generated by Django 5.1.3 on 2025-01-03 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_place_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="place",
            table="place",
        ),
    ]
