# Generated by Django 5.1.3 on 2025-01-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_customuser_options_alter_customuser_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customuser",
            table="main_customuser",
        ),
    ]
