# Generated by Django 5.1.2 on 2025-01-07 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_bookmark_id_bookmark_bookmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='country',
            field=models.ForeignKey(default='US', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.country'),
        ),
    ]
