# Generated by Django 5.1.2 on 2025-01-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_settings_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country_id',
            field=models.CharField(blank=True, default='US', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='thumbnail_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
