# Generated by Django 5.1.2 on 2025-01-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Not Specified'), (1, 'Male'), (2, 'Female')], default=0),
        ),
    ]
