# Generated by Django 5.1.2 on 2025-01-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatting',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
