# Generated by Django 5.1.4 on 2025-01-16 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_schedule_place_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarklist',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.schedule'),
        ),
        migrations.AlterField(
            model_name='bookmarklist',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.place'),
        ),
    ]
