# Generated by Django 5.1.4 on 2025-01-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_bookmarklist_schedule_alter_bookmarklist_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarklist',
            name='day_num',
        ),
        migrations.RemoveField(
            model_name='bookmarklist',
            name='order',
        ),
    ]
