# Generated by Django 5.1.4 on 2025-01-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_bookmarklist_day_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
