# Generated by Django 5.1.4 on 2025-01-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_schedule_json_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='BookmarkPlace',
        ),
        migrations.RenameModel(
            old_name='Schedule',
            new_name='BookmarkSchedule',
        ),
    ]
