# Generated by Django 5.1.4 on 2025-01-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_place_bookmarkplace_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarklist',
            old_name='place',
            new_name='bookmarkplace',
        ),
        migrations.RenameField(
            model_name='bookmarklist',
            old_name='schedule',
            new_name='bookmarkschedule',
        ),
        migrations.RenameField(
            model_name='bookmarkplace',
            old_name='place_id',
            new_name='bookmarkplace_id',
        ),
        migrations.RenameField(
            model_name='bookmarkschedule',
            old_name='schedule_id',
            new_name='bookmarkschedule_id',
        ),
    ]
