# Generated by Django 5.1.4 on 2025-01-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_place_bookmarklist_bookmarkplace_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmarkplace',
            table='bookmarkplace',
        ),
        migrations.AlterModelTable(
            name='bookmarkschedule',
            table='bookmarkschedule',
        ),
    ]
