# Generated by Django 5.1.4 on 2025-01-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_bookmarkplace_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkplace',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookmarkplace',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmarkplace',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
