# Generated by Django 5.1.4 on 2025-02-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_bookmarkplace_name_alter_bookmarkschedule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkplace',
            name='address',
            field=models.CharField(max_length=80),
        ),
    ]
